name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn --version
    - name: Run a multi-line script
      run: |
        echo Hello World!
        echo First test with Maven Action
        sudo apt-get -y install screenfetch
        screenfetch
        df -h
        bash --version
